Repository painterjd/stoplight, pull requests merged in 2019-02, with the labels that each got.

#20 Avoid DeprecationWarning on Python 3
  stoplight/decorators.py
  stoplight/rule.py
Labels: bug

#21 Bug Fix: Setup fix and Py37 support
  .travis.yml
  setup.py
  tox.ini
Labels: bug, enhancement

#23 Version Bump: 1.4.0 -> 1.4.1
  setup.py
Labels: enhancement
